config/routes.rb
Smile::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'entities#index'
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "entities#index"

  match "/signout" => "sessions#destroy", :as => :signout
  match "/login/:auth_key"   => "sessions#login", :as => :login
  match "/feed" => "entities#index"

  match "anecdots" => redirect("/?type=anecdot"), :as => :anecdots
  match "statuses" => redirect("/?type=status"), :as => :statuses

  resources :entities do
    member do
      post :approve
    end
  end
  resources :comments
  resources :users
  resources :votes, :only => [:create]
  resources :favorites, :only => [:index, :create, :destroy]

end

app/models/entity.rb
# -*- coding: utf-8 -*-
class Entity < ActiveRecord::Base
  APPROVED_STATUS = 'approved'
  DELETED_STATUS = 'deleted'
  NOT_APPROVED_STATUS = 'not_approved'

  before_validation :clear_content_and_set_status

  belongs_to :user
  belongs_to :category
  has_many :comments, :dependent => :delete_all
  has_many :votes, :dependent => :delete_all

  validates :content,     :presence  => true
  validate :check_type

  scope :approved, where(:status => APPROVED_STATUS)
  scope :recent,   order('updated_at DESC')
  scope :popular,  order('rating DESC')

  def not_approved?
    self.status == NOT_APPROVED_STATUS
  end

  def check_type
    errors.add(:type, 'имеет не корректное значение.') unless EntityType.all.map(&:code).include?(self.type)
  end

protected
  def clear_content_and_set_status
    self.content = self.content.to_s.gsub(/\s+/, ' ').strip
    self.status = self.user.is_admin? ? APPROVED_STATUS : NOT_APPROVED_STATUS
  end

end

app/models/entity_type.rb
class EntityType < ActiveRecord::Base
  has_many :categories
end

app/controllers/entities_controller.rb
# -*- coding: utf-8 -*-
class EntitiesController < ApplicationController
  before_filter :require_login, :only => [:create]
  before_filter :set_entity, :require_admin, :only => [:approve, :destroy]

  def index
    @entities = entities_type.includes(:user).page(params[:page]).per_page(20)
    unless is_admin?
      @entities = @entities.approved
    end
    if params[:category_id] and @category = Category.find(params[:category_id])
      @entities = @entities.where(:category_id => @category.id)
    end
    @entities = entities_order
    if is_logged?
      current_user.voted_store = current_user.voted_entities.where(:id => @entities.map(&:id))
      current_user.favorite_store = current_user.favorite_entities.where(:id => @entities.map(&:id))
    end
  end

  def show
    @entity = Entity.includes(:user, :comments => :user).find params[:id]
    if is_logged?
      current_user.voted_store = current_user.voted_entities.where(:id => @entity.id)
      current_user.favorite_store = current_user.favorite_entities.where(:id => @entity.id)
    end
  #rescue ActiveRecord::RecordNotFound
  #  redirect_to root_path, :alert => 'Запрашиваемая страница не найдена.'
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = current_user.entities.build params[:entity]
    @entity.type = params[:entity][:type]
    @entity.save
  end

  def approve
    render :json => { :success => @entity.update_attribute(:status, Entity::APPROVED_STATUS) }
  end

  def destroy
    @entity.destroy
    render :json => { :success => true }
  end

  private

  def entities_order
    case params[:order]
      when 'popular' then @entities.popular
      else @entities.recent
    end
  end

  def entities_type
    case params[:type]
      when 'anecdot' then Anecdot
      when 'status'  then Status
      else Entity
    end
  end

  def set_entity    
    @entity = Entity.find params[:id]
  end

end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<div id="entity_<%= entity.id %>" class="entity">
  <table>
    <tr>
      <td class="image"><%= image_tag entity.user.avatar_url, :size => '50x50' %></td>
      <td class="info">
        <div class="entity_content">
          <% if entity.created_at.strftime('%Y-%m-%d') == Time.now.strftime('%Y-%m-%d') %>
            <span class="label success">New</span>
          <% end %>
          <% if controller?('entities') and action?('index') and params[:type].nil? %>
            <% if entity.type == 'Status' %>
              <span class="label notice">Статус</span>
            <% elsif entity.type == 'Anecdot' %>
              <span class="label important">Анекдот</span>
            <% end %>
          <% end %>
          <%= link_to h(entity.user.full_name), entity.user.auth_url, :class => 'author', :target => 'blank' %>
          <div class="pull-right">
            <% if is_admin? && entity.not_approved? %>
              <%= link_to 'Утвердить', approve_entity_path(entity), :class => 'approve_link', :method => 'post', :remote => true %>
            <% end %>
            <% if is_admin? %>
              <%= link_to 'Удалить', entity_path(entity), :class => 'remove_link', :confirm => 'Вы согласны?', :method => 'delete', :remote => true %>
            <% end %>
          </div>
          <a class="entity_text" href="<%= entity_path(entity)%>" title="Читать полностью">
            <%=raw nl2br(h entity.content) %>
          </a>
        </div>
        <div class="entity_footer">
          <div class="pull-left">
            <span><%= Russian::strftime(entity.created_at, '%d %b в %H:%M') %></span>
            <%= render :partial => 'shared/add_to_favorites', :locals => { :entity => entity } if is_logged? %>
            <span class="replay_entity">
              <span>|</span>
              <%= link_to "Комментировать (#{entity.comment_count})", new_comment_path(:entity_id => entity.id), :remote => true %>
            </span>
          </div>
          <%= render :partial => 'shared/voting', :locals => { :entity => entity } %>
          <br class="clear" />
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/entities/_form.html.erb
<div>
  <%= form_for @entity, :remote => true do |f| %>
    <%= render :partial => 'shared/form_errors', :locals => { :errors => @entity.errors } if @entity.errors.any?%>
    <div class="clearfix">
      <%= f.label :type %>
      <div class="input"><%= f.collection_select :type, EntityType.order(:name), :code, :name, :class => 'xlarge'%></div>
    </div>
    <div class="clearfix">
      <%= f.label :content %>
      <div class="input"><%= f.text_area :content, :rows => 5, :class => 'xlarge' %></div>
    </div>
    <div class="clearfix">
      <%= f.label :category_id %>
      <div class="input">
        <%= f.grouped_collection_select :category_id, EntityType.order(:name), :categories, :code, :id, :name, :class => 'xlarge' %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Сохранить', :class => 'btn primary' %>
    </div>
  <% end %>
</div>

app/views/entities/_full_entity.html.erb
<div id="entity_<%= @entity.id %>" class="entity">
  <table>
    <tr>
      <td class="image"><%= image_tag @entity.user.avatar_url, :size => '50x50' %></td>
      <td class="info">
        <div class="entity_content">
          <% if @entity.created_at.strftime('%Y-%m-%d') == Time.now.strftime('%Y-%m-%d') %>
            <span class="label success">New</span>
          <% end %>
          <%= link_to h(@entity.user.full_name), @entity.user.auth_url, :class => 'author', :target => 'blank' %>
          <div class="pull-right">
            <% if is_admin? && @entity.not_approved? %>
              <%= link_to 'Утвердить', approve_entity_path(@entity), :class => 'approve_link', :method => 'post', :remote => true %>
            <% end %>
            <% if is_admin? %>
              <%= link_to 'Удалить', entity_path(@entity), :class => 'remove_link', :confirm => 'Вы согласны?', :method => 'delete', :remote => true %>
            <% end %>
          </div>
          <div>
            <%=raw nl2br(h @entity.content) %>
          </div>
        </div>
        <div class="entity_footer">
          <div class="pull-left">
            <span><%= Russian::strftime(@entity.created_at, '%d %b в %H:%M') %></span>
            <%= render :partial => 'shared/add_to_favorites', :locals => { :entity => @entity } if is_logged? %>
            <div class="social-button">
              <!-- AddThis Button BEGIN -->
              <div class="addthis_toolbox addthis_default_style ">
              <a class="addthis_button_preferred_1"></a>
              <a class="addthis_button_preferred_2"></a>
              <a class="addthis_button_preferred_3"></a>
              <a class="addthis_button_preferred_4"></a>
              <a class="addthis_button_compact"></a>
              <a class="addthis_counter addthis_bubble_style"></a>
              </div>
              <!-- AddThis Button END -->
            </div>
          </div>
          <%= render :partial => 'shared/voting', :locals => { :entity => @entity } %>
          <br class="clear" />
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/entities/_small_entity.html.erb
<div id="entity_<%= entity.id %>" class="entity">
  <table>
    <tr>
      <td>
        <div class="entity_content">
          <% if entity.created_at.strftime('%Y-%m-%d') == Time.now.strftime('%Y-%m-%d') %>
            <span class="label success">New</span>
          <% end %>
          <% if entity.type == 'Status' %>
            <span class="label notice">Статус</span>
          <% elsif entity.type == 'Anecdot' %>
            <span class="label important">Анекдот</span>
          <% end %>
          <span>от <%= link_to h(entity.user.full_name), entity.user.auth_url, :class => 'author', :target => 'blank' %></span>
          <div class="pull-right">
            <%= link_to 'Удалить из избранного', favorite_path(entity), :class => 'remove_link', :confirm => 'Вы согласны удалить из избранного?', :method => 'delete', :remote => true %>
          </div>
          <a class="entity_text" href="<%= entity_path(entity)%>" title="Читать полностью">
            <%=raw nl2br(h entity.content) %>
          </a>
        </div>
        <div class="entity_footer">
          <div class="pull-left">
            <span><%= Russian::strftime(entity.created_at, '%d %b в %H:%M') %></span>
          </div>
          <div class="pull-right">
            <span><i class="icon-heart"></i> <%=entity.rating%></span>
          </div>
          <br class="clear" />
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/entities/create.js.erb
<% if (@entity.errors.present?) %>
  if ($('#new_entity div.error_explanation').length) {
    $('#new_entity div.error_explanation').replaceWith('<%= j render :partial => 'shared/form_errors', :locals => { :errors => @entity.errors }%>');
  } else {
    $('#new_entity').prepend('<%= j render :partial => 'shared/form_errors', :locals => { :errors => @entity.errors }%>');
  }
<% else %>
  $('#modal-form').modal('hide');
  $('#new_entity').slideDown(1000, function() { $(this).remove(); });
  $('#content div.row').prepend($('<%= j content_tag :div,  "Запись успешно добавлена. #{is_admin? ? '' : 'Ожидается проверки модератора.'}", :class => "alert-message alert"%>'));
  $('div.alert-message').flashMessage();
<% end %>

app/views/entities/index.html.erb
<div id="entities">
  <% if params[:type].nil? %>
    <% title 'Новинки смешного дня' %>
    <% page_title 'Лента' %>
  <% elsif params[:type] == 'anecdot' %>
    <% title 'Отличные Анекдоты' %>
    <% page_title 'Все Анекдоты' %>
  <% elsif params[:type] == 'status' %>
    <% title 'Отличные Статусы' %>
    <% page_title @category ? "#{@category.name} cтатусы" : 'Все Статусы' %>
  <% end %>
  <%= render :partial => 'entities/entity', :collection => @entities %>
</div>
<%= will_paginate @entities  %>

<% if params[:type] == 'status' %>
  <% content_for :left_side do %>
    <%= render :partial => 'shared/categories', :locals => { :categories => Category.find_all_by_entity_type_id(2) } %>
  <% end %>
<% end %>

app/views/entities/index.js.erb
$('#entities').append('<%= j render :partial => 'entities/entity', :collection => @entities %>').find('div.entity_text').expander({expandText: 'читать полностью', userCollapse: false, slicePoint: 300});
<% if @entities.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @entities %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/entities/new.js.erb
<% if is_logged? %>
  if ($('#new_entity').length == 0) {
    $('#modal-form div.form').html('<%= j render('form')%>');
    var categories = $('#entity_category_id').html(),
        categoryParent = $('#entity_category_id').parents('div.clearfix');
      categoryParent.hide();
    $('#entity_type').change(function() {
      var type = $(this).val(),
          escaped_type = type.replace(/([ #;&,.+*~\':"!^$[\]()=>|\/@])/g, '\\$1');
      var options = $(categories).filter('optgroup[label=' + escaped_type + ']').html();
      if (options) {
        $('#entity_category_id').html(options);
        categoryParent.show();
      } else {
        $('#entity_category_id').empty();
        categoryParent.hide();
      }
    });
    $('#new_entity').customFormSubmit();
  }
  $('#modal-form').modal('show');
<% else %>
  if ($('#content div.alert-message').length == 0) {
    $($('#content div.row').children()[0]).prepend($('<%= j content_tag :div,  "Вы должны авторизироваться чтобы создавать записи.", :class => "alert-message "%>'));
  }
  $('div.alert-message').flashMessage();
<% end %>

app/views/entities/show.html.erb
<% if @entity.type == 'Anecdot' %>
  <% title 'Отличный Анекдот'%>
  <% page_title 'Анекдот'%>
<% elsif @entity.type == 'Status' %>
  <% title 'Отличный статус'%>
  <% page_title 'Статус' %>
<% end %>

<%= render 'full_entity' %>
<div id="comments">
  <div class="comments-content">
    <%= render @entity.comments %>
  </div>
  <% if is_logged? %>
    <% @comment = @entity.comments.build %>
    <%= render 'comments/form' %>
  <% else %>
    <div>Чтобы комментировать запись Вы должны авторизироваться .</div>
  <% end %>
</div>