config/routes.rb
Smile::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'entities#index'
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "entities#index"

  match "/signout" => "sessions#destroy", :as => :signout
  match "/login/:auth_key"   => "sessions#login", :as => :login
  match "/feed" => "entities#index"

  match "anecdots" => redirect("/?type=anecdot"), :as => :anecdots
  match "statuses" => redirect("/?type=status"), :as => :statuses

  resources :entities do
    member do
      post :approve
    end
  end
  resources :comments
  resources :users
  resources :votes, :only => [:create]
  resources :favorites, :only => [:index, :create, :destroy]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  after_create { |admin| admin.send_reset_password_instructions }

  def password_required?
    new_record? ? false : super
  end
end

app/models/anecdot.rb
class Anecdot < Entity

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :anecdots
  has_many :statuses
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :entity

  after_destroy :decrease_comment_count
  after_create  :increase_comment_count

  validates_presence_of :content

  before_validation :trim_content

  def trim_content
    self.content = self.content.gsub(/\s+/, ' ').strip
  end

  protected

  def decrease_comment_count
    Entity.update_counters(self.entity_id, :comment_count => -1)
  end

  def increase_comment_count
    Entity.update_counters(self.entity_id, :comment_count => 1)
  end
end

app/models/entity.rb
# -*- coding: utf-8 -*-
class Entity < ActiveRecord::Base
  APPROVED_STATUS = 'approved'
  DELETED_STATUS = 'deleted'
  NOT_APPROVED_STATUS = 'not_approved'

  before_validation :clear_content_and_set_status

  belongs_to :user
  belongs_to :category
  has_many :comments, :dependent => :delete_all
  has_many :votes, :dependent => :delete_all

  validates :content,     :presence  => true
  validate :check_type

  scope :approved, where(:status => APPROVED_STATUS)
  scope :recent,   order('updated_at DESC')
  scope :popular,  order('rating DESC')

  def not_approved?
    self.status == NOT_APPROVED_STATUS
  end

  def check_type
    errors.add(:type, 'имеет не корректное значение.') unless EntityType.all.map(&:code).include?(self.type)
  end

protected
  def clear_content_and_set_status
    self.content = self.content.to_s.gsub(/\s+/, ' ').strip
    self.status = self.user.is_admin? ? APPROVED_STATUS : NOT_APPROVED_STATUS
  end

end

app/models/entity_type.rb
class EntityType < ActiveRecord::Base
  has_many :categories
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :entity
end

app/models/status.rb
class Status < Entity
  belongs_to :category

  validates_presence_of :category_id

end

app/models/user.rb
class User < ActiveRecord::Base
  ADMIN_ROLE  = 'admin'
  USER_ROLE   = 'user'
  SEX = {
      :male   => 'male',
      :female => 'female',
      :none   => 'none'
  }

  attr_accessor :voted_store, :favorite_store

  has_many :entities
#  has_many :statuses
#  has_many :anecdots
  has_many :votes
  has_many :voted_entities, :class_name => 'Entity', :through => :votes, :source => :entity
  has_many :comments
  has_many :favorites, :dependent => :destroy
  has_many :favorite_entities, :class_name => 'Entity', :through => :favorites, :source => :entity

  def self.create_from_vk(auth_params)
    create! do |user|
      user_data = auth_params['extra']['raw_info']
      user.auth_key = auth_params['uid']
      user.firstname = user_data['first_name']
      user.lastname = user_data['last_name']
      user.auth_type = auth_params['provider']
      user.auth_url = 'http://vkontakte.ru/id' + auth_params['uid'].to_s
      user.role = USER_ROLE
      user.sex = user_data['sex'] == 2 ? SEX[:male] : (user_data['sex'] == 1 ? SEX[:female] : SEX[:none])
      user.description = ''
      user.rating = 0
      user.avatar_url = user_data['photo']
      user.big_photo_url = user_data['photo_big']
    end
  end

  def is_admin?
    self.role == ADMIN_ROLE
  end

  def full_name
    self.firstname + ' ' + self.lastname
  end

end

app/models/vk.rb
require 'digest/md5'
require 'json'
class Vk
  API_URL = 'http://api.vkontakte.ru/api.php'
  API_ID = '2707091'
  SECRET_KEY = 'ReufrpuncHLii3kpVFnS'

  def self.check?(hash_params)
    hash_params[:api_url].to_s == API_URL && Digest::MD5::hexdigest("#{API_ID}_#{hash_params[:viewer_id]}_#{SECRET_KEY}") == hash_params[:auth_key]
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  after_create :increment_entity_rating
  belongs_to :user
  belongs_to :entity

  def increment_entity_rating
  	Entity.update_counters(self.entity_id, :rating => self.rating)
  end  
end

app/helpers/anecdots_helper.rb
module AnecdotsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_user_menu.html.erb
<li class="dropdown" data-dropdown="dropdown">
  <!--<%= image_tag current_user.avatar_url, :size => '24x24' %>-->
  <a class="dropdown-toggle">
    <span class="full_name"><%= current_user.full_name %></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Избранное', favorites_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Выйти', signout_path %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><%= h(yield(:title) || 'Смешной день') %></title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/assets/icon.ico">
    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f3956894d0352b6"></script>
  </head>
  <body>
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <%= link_to root_url, :class => 'brand' do %>
            <img src="/assets/logo.png" alt="Смешной день" width="20" height="20" title="Смешной день" />
            Смешной День
          <% end %>
          <ul class="nav">
            <%= nav_link 'Анекдоты', '/anecdots', (controller?('entities') and params[:type] == 'anecdot') %>
            <%= nav_link 'Статусы', '/statuses', (controller?('entities') and params[:type] == 'status') %>
          </ul>
          <ul class="nav secondary-nav" id="right_navigation">
            <% if is_logged? %>
              <%= render 'layouts/user_menu' %>
            <% else %>
              <li class="auth_icon">
                <a href="/auth/vkontakte" title="Войти через ВКонтакте">
                  <%= image_tag 'vkontakte_32.png', :size => "32x32" %>
                </a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div id="content" class="content">
        <% if content_for?(:page_title) %>
          <div class="page-header">
            <h1><%= h(yield :page_title) %></h1>
            <div class="pull-right">
              <%= link_to 'Добавить', new_entity_path, :remote => true, :class => 'btn primary' %>
            </div>
          </div>
        <% end %>
        <div class="row">
          <div class="span<%= content_for?(:left_side) ? '10' : '14' %>">
            <% flash.each do |key, msg| %>
              <%= content_tag :div, msg, :class => "alert-message #{(key == :notice) ? 'success' : key}"%>
            <% end %>
            <% if controller?('entities') and action?('index') %>
              <div class="head-manage-menu">
                <span><%= link_to_unless(params[:order] != 'popular', 'Новые', params.merge(:order => nil, :page => nil)) %></span>
                <span><%= link_to_unless(params[:order] == 'popular', 'Популярные', params.merge(:order => 'popular', :page => nil)) %></span>
              </div>
            <% end %>
            <%= yield %>
          </div>
          <% if content_for? :left_side %>
            <div class="span4"><%=raw yield(:left_side) %></div>
          <% end  %>
        </div>
      </div>
      <footer>
        <p>&copy; Отличное настроение <%= Time.now.year %></p>
      </footer>
    </div> <!-- /container -->
    <div id="modal-form" class="modal hide fade">
      <div class="modal-header">
        <a data-dismiss="modal" class="close">&times;</a>
        <h3>Новая запись</h3>
      </div>
      <div class="modal-body">
        <div class="form"></div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_add_to_favorites.html.erb
<% if !current_user.favorite_store.include?(entity) %>
  <span class="add-to-favorites">
    <span>|</span>
    <%= link_to 'Добавить в избранное', favorites_path(:entity_id => entity.id), :class => 'favorite_link', :title => 'Добавить в избранное', :method => 'post', :remote => true %>
  </span>
<% end %>

app/views/shared/_categories.html.erb
<div class="category">
  <h3>Категории</h3>
  <ul>
    <% categories.each do |category| %>
      <li><%= link_to_unless(params[:category_id].to_i == category.id, category.name, params.merge(:category_id => category.id, :page => nil)) %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_form_errors.html.erb
<div class="error_explanation">
  <ul>
    <% errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_voting.html.erb
<div id="voting_<%= entity.id %>" class="pull-right">
  <% if is_logged? and !current_user.voted_store.include?(entity) %>
  	<%= link_to content_tag(:i, '', :class => 'icon-plus'), votes_path(:entity_id => entity.id, :rate => 'plus'), :title => 'Проголосовать за', :rel => 'tooltip', :method => 'post', :remote => true %>
  	<%= link_to content_tag(:i, '', :class => 'icon-minus'), votes_path(:entity_id => entity.id, :rate => 'minus'), :title => 'Проголосовать против', :rel => 'tooltip', :method => 'post', :remote => true %>
  <% end %>
  <span><i class="icon-heart"></i> <%= entity.rating%></span>
</div>